# Generated by Django 5.0.6 on 2024-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('puntos', models.IntegerField(default=0)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('preferencia_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('idioma_preferido', models.CharField(blank=True, max_length=50, null=True)),
                ('recibir_notificaciones', models.BooleanField(default=True)),
                ('historial_reservas', models.TextField(blank=True, null=True)),
                ('preferencias_habitaciones', models.TextField(blank=True, null=True)),
                ('notas_especiales', models.TextField(blank=True, null=True)),
                ('ultima_fecha_acceso', models.DateTimeField(blank=True, null=True)),
                ('estado_cuenta', models.CharField(default='activo', max_length=20)),
                ('preferencias_viaje', models.TextField(blank=True, null=True)),
                ('comentarios_valoraciones', models.TextField(blank=True, null=True)),
                ('consentimiento_marketing', models.BooleanField(default=True)),
                ('logs_actividad', models.TextField(blank=True, null=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.role')),
            ],
        ),
    ]
