# Generated by Django 5.0.6 on 2024-06-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='consentimiento_marketing',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado_cuenta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idioma_preferido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='logs_actividad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='notas_especiales',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='preferencia_contacto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='preferencias_habitaciones',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='preferencias_viaje',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='recibir_notificaciones',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_fecha_acceso',
        ),
    ]
