# Generated by Django 5.0.6 on 2024-06-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_alter_hotel_porcentaje_descuento'),
        ('usuarios', '0006_tarjetapuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='hoteles_vistos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_que_han_visto', to='hoteles.hotel'),
        ),
    ]
