# Generated by Django 5.0.6 on 2024-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_hoteles_vistos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='hoteles_vistos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='hoteles_vistos_ids',
            field=models.TextField(blank=True, verbose_name='IDs de hoteles visitados'),
        ),
    ]
