# Generated by Django 5.0.6 on 2024-07-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_usuario_hoteles_vistos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='historial_reservas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
