# Generated by Django 5.0.6 on 2024-07-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_usuario_historial_reservas_usuario_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='lista_cupones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
