# Generated by Django 4.1.2 on 2024-06-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion_breve', models.CharField(max_length=500)),
                ('descripcion_detallada', models.TextField()),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(upload_to='hoteles/')),
            ],
        ),
    ]
