# Generated by Django 5.0.6 on 2024-06-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='categoria',
            field=models.CharField(choices=[('normal', 'Normal'), ('frente_al_mar', 'Frente al Mar'), ('cabanas', 'Cabañas')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='en_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='porcentaje_descuento',
            field=models.FloatField(default=0.0),
        ),
    ]
