# Generated by Django 5.0.6 on 2024-06-28 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_alter_hotel_porcentaje_descuento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='stock_habitaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('cantidad_camas', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hoteles.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('cantidad_habitaciones', models.PositiveIntegerField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.habitacion')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.hotel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
