# Generated by Django 5.0.6 on 2024-06-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0004_hotel_stock_habitaciones_habitacion_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad_habitaciones',
        ),
    ]
