# Generated by Django 5.0.6 on 2024-06-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0005_remove_reserva_cantidad_habitaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
    ]
