# Generated by Django 5.0.6 on 2024-06-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0007_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='id',
        ),
        migrations.AddField(
            model_name='valoracion',
            name='valoracion_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
