# Generated by Django 5.0.6 on 2024-06-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0008_remove_valoracion_id_valoracion_valoracion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
