# Generated by Django 5.0.6 on 2024-07-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0010_hotel_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='desayuno_incluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='gimnasio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='piscina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='restaurante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='servicio_conserjeria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='servicio_transporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='servicios_eventos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='spa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi_gratuito',
            field=models.BooleanField(default=False),
        ),
    ]
